import { useEffect, useState } from "react";
import { api } from "@/api/client";
import { AppShell, Card, Button, StatTile } from "@/components";
import type { WeeklyPlan } from "@/types/api";

export default function Dashboard() {
  const [plan, setPlan] = useState<WeeklyPlan | null>(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    api
      .getPlan()
      .then((r) => setPlan(r.plan))
      .catch((err) => {
        console.error("Failed to load plan:", err);
        setPlan(null);
      });
  }, []);

  async function handleGenerate() {
    setGenerating(true);
    setError(null);

    try {
      const r = await api.generatePlan({ force: true });
      setPlan(r.plan);
    } catch (e) {
      setError(
        e instanceof Error ? e.message : "Could not generate your plan",
      );
    } finally {
      setGenerating(false);
    }
  }

  return (
    <AppShell active="/dashboard">
      <div style={{ display: "grid", gap: "var(--sp-6)" }}>
        <h1 style={{ fontSize: "var(--fs-3xl)" }}>
          Good Morning ??
        </h1>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(4, 1fr)",
            gap: "var(--sp-4)",
          }}
        >
          <StatTile label="Calories" value="1,890" unit="/ 2,300 kcal" delta={12} />
          <StatTile label="Workout" value="45" unit="/ 60 min" delta={8} />
          <StatTile label="Water" value="6" unit="/ 8 glasses" delta={-2} />
          <StatTile
            label="Weight"
            value="72.5"
            unit="kg"
            delta={-1.2}
            deltaLabel="vs last week"
          />
        </div>

        <Card title="This week's plan">
          {error && (
            <p style={{ color: "var(--c-danger)" }}>
              {error}
            </p>
          )}

          {!plan ? (
            <p style={{ color: "var(--c-text-secondary)" }}>
              No plan yet — generate your first one.
            </p>
          ) : (
            <>
              {plan.generationSource === "fallback" && (
                <p
                  style={{
                    color: "var(--c-warning)",
                    fontSize: "var(--fs-sm)",
                    marginBottom: "var(--sp-4)",
                  }}
                >
                  Generated by static fallback. AI generation is currently pending AWS verification.
                </p>
              )}

              {plan.coachNote && (
                <p style={{ marginBottom: "var(--sp-6)" }}>
                  {plan.coachNote}
                </p>
              )}

              <h2
                style={{
                  fontSize: "var(--fs-xl)",
                  marginBottom: "var(--sp-4)",
                }}
              >
                Workout Plan
              </h2>

              <div style={{ display: "grid", gap: "var(--sp-4)" }}>
                {(plan.workoutPlan ?? []).map((day) => (
                  <div
                    key={day.day}
                    style={{
                      border: "1px solid var(--c-border)",
                      borderRadius: "var(--r-md)",
                      padding: "var(--sp-4)",
                    }}
                  >
                    <h3 style={{ marginBottom: "var(--sp-2)" }}>
                      Day {day.day}: {day.title}
                    </h3>

                    <p
                      style={{
                        color: "var(--c-text-secondary)",
                        fontSize: "var(--fs-sm)",
                      }}
                    >
                      {day.isRestDay
                        ? "Rest day"
                        : `${day.durationMin} min • ~${day.estCalories} kcal`}
                    </p>

                    {!day.isRestDay && (
                      <ul
                        style={{
                          marginTop: "var(--sp-3)",
                          paddingLeft: "var(--sp-5)",
                        }}
                      >
                        {(day.exercises ?? []).map((exercise, index) => (
                          <li key={`${exercise.name}-${index}`}>
                            <strong>{exercise.name}</strong>
                            {" — "}
                            {exercise.sets} × {exercise.reps}
                            {" • "}
                            {exercise.restSeconds}s rest
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                ))}
              </div>

              <h2
                style={{
                  fontSize: "var(--fs-xl)",
                  marginTop: "var(--sp-8)",
                  marginBottom: "var(--sp-4)",
                }}
              >
                Meal Plan
              </h2>

              <div style={{ display: "grid", gap: "var(--sp-4)" }}>
                {(plan.mealPlan ?? []).map((day) => (
                  <div
                    key={day.day}
                    style={{
                      border: "1px solid var(--c-border)",
                      borderRadius: "var(--r-md)",
                      padding: "var(--sp-4)",
                    }}
                  >
                    <h3>Day {day.day}</h3>

                    <p
                      style={{
                        color: "var(--c-text-secondary)",
                        fontSize: "var(--fs-sm)",
                        marginBottom: "var(--sp-3)",
                      }}
                    >
                      {day.totalCalories} kcal • {day.totalProteinG}g protein
                    </p>

                    <ul style={{ paddingLeft: "var(--sp-5)" }}>
                      {(day.meals ?? []).map((meal, index) => (
                        <li key={`${meal.name}-${index}`}>
                          <strong>{meal.slot}:</strong> {meal.name}
                          {" — "}
                          {meal.calories} kcal • {meal.proteinG}g protein
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
            </>
          )}

          <Button
            onClick={handleGenerate}
            disabled={generating}
          >
            {generating ? "Generating..." : "Generate New Plan ?"}
          </Button>
        </Card>
      </div>
    </AppShell>
  );
}
